#! /bin/sh

mkdir -p docroot/cgi-bin
cat >docroot/cgi-bin/env.cgi <<EOF
#!/bin/sh
echo "Content-Type: text/plain"
echo

env
EOF
chmod a+rx docroot/cgi-bin/env.cgi
echo "just a text file" > docroot/docroot/file
cd docroot
ftp https://stevens.netmeister.org/631/makelstest
sh makelstest
echo "<html><head><title>Welcome!</title></head><body><h1>Boring HTML</h1></body></html>" >index.html
mkdir ~/sws
echo "a file in my personal webspace" > ~/sws/file
